# Generated by Django 6.0.5 on 2026-06-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_roadmap'),
        ('tasks', '0002_alter_task_options_task_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='planner.roadmap'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
