# Generated by Django 6.0.5 on 2026-06-30 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phases', models.JSONField(default=list)),
                ('tasks', models.JSONField(default=list)),
                ('available_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('energy_level', models.CharField(blank=True, max_length=20, null=True)),
                ('deadline', models.CharField(blank=True, max_length=20, null=True)),
                ('work_style', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
